### ISSUE TITLE
Package doesn't include bundled dist

### ISSUE THREAD

**Issue by loremipson** [waspeer/sanity-plugin-iconify#1]
The built dist folder is not included when installing the package, so imports do not resolve.

**Comment by waspeer** [comment]
Oh snap, that's a bummer. I'll get on this in a bit! Thanks for letting me know

**Comment by waspeer** [comment]
This should be fixed now! Had to run so I couldn't install it myself to test, but the dist folder is there now. I'll check it tomorrow. Please let me know if it works for you.

**Comment by loremipson** [comment]
Seems to work, that was fast, thank you.
