### ISSUE TITLE
Change the icon size in the selection list

### ISSUE THREAD

**Issue by hrvstr** [waspeer/sanity-plugin-iconify#3]
Hi, first off, thank you for this plugin! I wanted to ask if changing the icon size in the selection list is possible? I am using the the Material Design icon set and the icons are really small and hard to read.

Thanks

![CleanShot 2023-11-01 at 17 53 03](https://github.com/waspeer/sanity-plugin-iconify/assets/4610008/ae83b3bf-9ad8-4dbd-9fc6-8b2009d3c6c9)

**Comment by waspeer** [comment]
Thanks for using it!
How much bigger are you thinking? This would be a bump from 1em to 1.2em.

<img width="633" alt="image" src="https://github.com/waspeer/sanity-plugin-iconify/assets/11842931/3ac046c0-4549-4638-acff-c2d8496d5476">

**Comment by hrvstr** [comment]
Ideally, I think this would be a setting but I am not sure how much effort that would be. 1.2 em is better but still on the small side, I think. At Iconify they display icons with a size of 48x48 px on desktops and I think they are easy to parse that way. Of course, their list is a bit larger in general.

![Bildschirmfoto 2023-11-02 um 08 41 44](https://github.com/waspeer/sanity-plugin-iconify/assets/4610008/c10f1055-bd4d-4fd1-9c12-69218c6aa589)

**Comment by waspeer** [comment]
I'm not completely sold on customizing the look of the combobox with granular settings like eg `iconSize`. While such settings offer immediate customization, they could lead us to an API that's cumbersome to maintain. For example, if we later would want to customize the padding between the icons or the number of icons per row this would affect the icon size as well and vice versa.

If the demand for customizability is there, I'd rather allow customization through components. Something like this:

```tsx
import { Button } from '@sanity/ui';
import { iconify } from 'sanity-plugin-iconify';

export default defineConfig({
  //...
  plugins: [iconify({
    components: {
      // Decreasing the padding on the wrapping button is one way to make the icons bigger
      option: ({ icon }) => <Button padding={0}>{icon}</Button>
    }
  })],
});
```

This would give us the flexibility to adapt the UI without bloating the API with too many specific settings. However, for the current issue, this might be too extensive a solution. I'm curious to hear your thoughts on this.

That said, I've been working on improvements for the grid layout that will also address the icon sizing. The new version (1.1.1) will make the icons slightly larger, roughly 1.5/1.7rem, depending on the browser. I'm interested to hear if this version resolves the issue for you after you have a chance to try it out.

**Comment by hrvstr** [comment]
Sure, your concerns about a bloated/difficult-to-maintain API sound reasonable. The component approach would work as well but I agree it would be a bit much just for changing the icon size. If the new version makes them a bit a bit larger that's totally fine. 

To be honest I am not really experienced in API design so I can't give you too much input here. I am really happy that this plugin exists in the first place. :)
