### ISSUE TITLE
Usage with icon field in defineType?

### ISSUE THREAD

**Issue by notflip** [waspeer/sanity-plugin-iconify#5]
Thanks for this repo, works perfect!

I'm wondering if it's possible to use these icons for the icon property of defineType, I tried the following but this throws errors

```
  name: 'newsCategory',
  type: 'document',
  title: 'News Category',
  icon: <Icon icon="material-symbols:account-circle-off-rounded" />,
```

**Comment by waspeer** [comment]
Glad it works well for you!

I'm not sure why this wouldn't work, but changing it to this is working for me:

```ts
  name: 'newsCategory',
  type: 'document',
  title: 'News Category',
  icon: () => <Icon icon="material-symbols:account-circle-off-rounded" />,
```

Does that help you in any way?

**Comment by waspeer** [comment]
Since this issue is not directly related to this plugin, but more to `sanity` and `@iconify/react` I'll close this for now. But let me know if you have any more questions or encounter any other issues!
